[package]
name = "generic-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { version = "1.5", features = ["derive"] }
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
